# -*- coding: utf-8 -*-
"""music-recomendation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2j1ReKsJnZMTFeHXNXNOQPZeSGbDVEy

###using Rule Association (Apyori)
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install apyori
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from apyori import apriori
# %matplotlib inline
import os

lastfm1 = pd.read_csv("https://www.biz.uiowa.edu/faculty/jledolter/DataMining/lastfm.csv")

lastfm = lastfm1.copy()
lastfm.head(2)

lastfm = lastfm[['user','artist']]
lastfm.head(2)

lastfm = lastfm.drop_duplicates()
lastfm.shape

records = []
for i in lastfm['user'].unique():
    records.append(list(lastfm[lastfm['user'] == i]['artist'].values))

for i in range(5):
  print(records[i][:5])

rules = apriori(records, min_support=0.01, min_confidence=0.4, min_lift=3, min_length=2)
results = list(rules)

print("There are {} Relation derived.".format(len(results)))

for item in results:
    # first index of the inner list
    # Contains base item and add item
    pair = item[0]
    items = [x for x in pair]
    print("Rule: With " +items[0] + " you can also listen " + items[1])

    # second index of the inner list
    print("Support: " + str(item[1]))

    # third index of the list located at 0th
    # of the third index of the inner list

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

